global:
  resolve_timeout: 5m
  http_config: {}
route:
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: "slack_general"
  group_by:
  - job
  routes:
  - receiver: "slack_general"
    match:
      alertname: DeadMansSwitch
receivers:
- name: slack_general
  slack_configs:
  - api_url: "https://hooks.slack.com/services/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"
    channel: '#prometheusalert'
    text: "<!channel> \nsummary: {{ .CommonAnnotations.summary }}\nmessage: {{ .CommonAnnotations.message }}\ndescription: {{ .CommonAnnotations.description }}"
